$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$OutDir = if ($env:OUT_DIR) { $env:OUT_DIR } else { Join-Path $Root 'dist/stress' }
$IntegrationRepeat = if ($env:INTEGRATION_REPEAT) { [int]$env:INTEGRATION_REPEAT } else { 3 }
$MixedRepeat = if ($env:MIXED_REPEAT) { [int]$env:MIXED_REPEAT } else { 20 }
$Timeout = if ($env:TIMEOUT) { $env:TIMEOUT } else { '20m' }
$Gomaxprocs = if ($env:GOMAXPROCS_VALUE) { $env:GOMAXPROCS_VALUE } else { '2' }
$RunBench = if ($env:RUN_BENCH) { $env:RUN_BENCH } else { '1' }

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

$IntegrationLog = Join-Path $OutDir 'integration-stress-run.log'
$MixedLog = Join-Path $OutDir ("realistic-pressure-x{0}.log" -f $MixedRepeat)
$BenchLog = Join-Path $OutDir 'metadata-bench-run.log'
$Report = Join-Path $OutDir 'stress-test-report.md'

$IntegrationRun = 'TestRealisticMixedBrowseSaveWatchPressure|TestMultiClientConcurrentCreateWriteRenameAndWatch|TestHeartbeatInterleavesWithFileOperations|TestConnectionJitterRepeatedResumeAndRead'
$BenchRun = 'BenchmarkMetadata(LookupHot|GetAttrHot|ReadDirSnapshotHit|ReadSmallFileCached|CreateWriteFlushClose)$'

function Invoke-LoggedNativeCommand {
  param(
    [string]$FilePath,
    [string[]]$Command
  )

  if (Test-Path $FilePath) {
    Remove-Item $FilePath -Force
  }

  $exe = $Command[0]
  $args = @()
  if ($Command.Length -gt 1) {
    $args = $Command[1..($Command.Length - 1)]
  }

  & $exe @args 2>&1 | ForEach-Object {
    $line = $_.ToString()
    Write-Host $line
    Add-Content -Path $FilePath -Value $line -Encoding UTF8
  }

  if ($LASTEXITCODE -ne 0) {
    throw ("command failed with exit code {0}: {1}" -f $LASTEXITCODE, ($Command -join ' '))
  }
}

Write-Host '==> integration stress suite'
$env:GOMAXPROCS = $Gomaxprocs
Invoke-LoggedNativeCommand -FilePath $IntegrationLog -Command @('go', 'test', './tests/integration', '-run', $IntegrationRun, '-count', $IntegrationRepeat.ToString(), '-timeout', $Timeout, '-v')

Write-Host ("==> realistic mixed workload x{0}" -f $MixedRepeat)
$env:GOMAXPROCS = $Gomaxprocs
Invoke-LoggedNativeCommand -FilePath $MixedLog -Command @('go', 'test', './tests/integration', '-run', '^TestRealisticMixedBrowseSaveWatchPressure$', '-count', $MixedRepeat.ToString(), '-timeout', $Timeout, '-v')

if ($RunBench -eq '1') {
  Write-Host '==> metadata backend benchmark'
  Invoke-LoggedNativeCommand -FilePath $BenchLog -Command @('go', 'test', './internal/server', '-run', '^$', '-bench', $BenchRun, '-benchmem', '-count', '3')
}

@"
# Stress test report

Generated by: scripts/run-stress-suite.ps1

## Commands

### Integration stress

```powershell
`$env:GOMAXPROCS = '$Gomaxprocs'
go test ./tests/integration -run '$IntegrationRun' -count $IntegrationRepeat -timeout $Timeout -v
```

### Mixed workload repeat

```powershell
`$env:GOMAXPROCS = '$Gomaxprocs'
go test ./tests/integration -run '^TestRealisticMixedBrowseSaveWatchPressure$' -count $MixedRepeat -timeout $Timeout -v
```

### Metadata benchmark

```powershell
go test ./internal/server -run '^$' -bench '$BenchRun' -benchmem -count 3
```

## Output files

- $IntegrationLog
- $MixedLog
- $BenchLog

The PowerShell wrapper preserves raw logs. For interpretation, see docs/architecture/test-report-iter43-stress-suite.md.
"@ | Set-Content -Path $Report -Encoding UTF8

Write-Host ("Stress suite complete. Logs and wrapper report written to {0}" -f $OutDir)
