#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT/dist/stress}"
INTEGRATION_REPEAT="${INTEGRATION_REPEAT:-3}"
MIXED_REPEAT="${MIXED_REPEAT:-20}"
TIMEOUT="${TIMEOUT:-20m}"
GOMAXPROCS_VALUE="${GOMAXPROCS_VALUE:-2}"
RUN_BENCH="${RUN_BENCH:-1}"

mkdir -p "$OUT_DIR"
cd "$ROOT"

INTEGRATION_LOG="$OUT_DIR/integration-stress-run.log"
MIXED_LOG="$OUT_DIR/realistic-pressure-x${MIXED_REPEAT}.log"
BENCH_LOG="$OUT_DIR/metadata-bench-run.log"
REPORT="$OUT_DIR/stress-test-report.md"

INTEGRATION_RUN='TestRealisticMixedBrowseSaveWatchPressure|TestMultiClientConcurrentCreateWriteRenameAndWatch|TestHeartbeatInterleavesWithFileOperations|TestConnectionJitterRepeatedResumeAndRead'
BENCH_RUN='BenchmarkMetadata(LookupHot|GetAttrHot|ReadDirSnapshotHit|ReadSmallFileCached|CreateWriteFlushClose)$'

printf '==> integration stress suite
' | tee "$INTEGRATION_LOG"
GOMAXPROCS="$GOMAXPROCS_VALUE" go test ./tests/integration   -run "$INTEGRATION_RUN"   -count "$INTEGRATION_REPEAT"   -timeout "$TIMEOUT"   -v | tee -a "$INTEGRATION_LOG"

printf '==> realistic mixed workload x%s
' "$MIXED_REPEAT" | tee "$MIXED_LOG"
GOMAXPROCS="$GOMAXPROCS_VALUE" go test ./tests/integration   -run '^TestRealisticMixedBrowseSaveWatchPressure$'   -count "$MIXED_REPEAT"   -timeout "$TIMEOUT"   -v | tee -a "$MIXED_LOG"

if [[ "$RUN_BENCH" == "1" ]]; then
  printf '==> metadata backend benchmark
' | tee "$BENCH_LOG"
  go test ./internal/server     -run '^$'     -bench "$BENCH_RUN"     -benchmem     -count 3 | tee -a "$BENCH_LOG"
fi

cat > "$REPORT" <<EOF
# Stress test report

Generated by: scripts/run-stress-suite.sh

## Commands

### Integration stress

\`\`\`bash
GOMAXPROCS=$GOMAXPROCS_VALUE go test ./tests/integration \
  -run '$INTEGRATION_RUN' \
  -count $INTEGRATION_REPEAT -timeout $TIMEOUT -v
\`\`\`

### Mixed workload repeat

\`\`\`bash
GOMAXPROCS=$GOMAXPROCS_VALUE go test ./tests/integration \
  -run '^TestRealisticMixedBrowseSaveWatchPressure$' \
  -count $MIXED_REPEAT -timeout $TIMEOUT -v
\`\`\`

### Metadata benchmark

\`\`\`bash
go test ./internal/server -run '^$' \
  -bench '$BENCH_RUN' -benchmem -count 3
\`\`\`

## Output files

- $(realpath --relative-to="$ROOT" "$INTEGRATION_LOG" 2>/dev/null || echo "$INTEGRATION_LOG")
- $(realpath --relative-to="$ROOT" "$MIXED_LOG" 2>/dev/null || echo "$MIXED_LOG")
- $(realpath --relative-to="$ROOT" "$BENCH_LOG" 2>/dev/null || echo "$BENCH_LOG")

The shell wrapper preserves raw logs. For interpretation, see docs/architecture/test-report-iter43-stress-suite.md.
EOF

echo "Stress suite complete. Logs and wrapper report written to $OUT_DIR"
